version: "3.9"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
    - 5432:5432

  postgres_marketplace:
    container_name: postgres_marketplace_ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: marketplace
      POSTGRES_PASSWORD: marketplace
    ports:
      - 5433:5432

  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - 9000:9000


  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8180:8080
    volumes:
      - .local/keycloak/:/opt/jboss/keycloak/standalone/data/

  jaeger_ifood:
    container_name: jaeger_ifood
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"

  prometheus_ifood:
    container_name: prometheus_ifood
    image: prom/prometheus:latest
    volumes:
      - .local/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090


  grafana_ifood:
    container_name: grafana_ifood
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    links:
      - prometheus_ifood

networks:
  default:
    driver: bridge