version: "3.9"
services:
  postgres_cadastro:
    container_name: postgres_cadastro_ifood
    image: postgres:12.2
    environment:
      POSTGRES_USER: cadastro
      POSTGRES_PASSWORD: cadastro
    ports:
    - 5432:5432

  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - 9000:9000


  keycloak_ifood:
    container_name: keycloak_ifood
    image: jboss/keycloak:latest
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    ports:
      - 8180:8080
    volumes:
    - .local/keycloak:/var/lib/keycloak/data

